name: Deploy

on:
  push:
    branch-ignore:
      - master
      - 'curl**'
    path:
      - '*.sh'

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Create deployment
        id: deployment
        run: |
          API_RESPONSE=$(curl -H "Accept: application/vnd.github.ant-man-preview+json" -H "Authorization: token ${{ github.token }}" -X POST -H 'Content-Type: application/json' -d '{"ref": "'"$GITHUB_REF"'", "environment": "preview", "transient_environment": true, "description": "My preview env", "required_contexts": []}' "https://api.github.com/repos/$GITHUB_REPOSITORY/deployments")
          STATUSES_URL=$(echo $API_RESPONSE | jq .statuses_url)
          echo "::set-output name=statuses_url::$STATUSES_URL"

      - name: Update deployment status (in_progress)
        run: |
          curl -H "Accept: application/vnd.github.flash-preview+json" -H "Authorization: token ${{ github.token }}" -X POST -H 'Content-Type: application/json' -d '{"state": "in_progress"}' ${{ steps.deployment.outputs.statuses_url }}

      - name: Deploy my app
        run: |
          echo done
          sleep 10
      
      - name: Update deployment status (success)
        if: success()
        run: |
          curl -H "Accept: application/vnd.github.ant-man-preview+json" -H "Authorization: token ${{ github.token }}" -X POST -H 'Content-Type: application/json' -d '{"state": "success", "description": "My success status", "environment_url": "https://gergely.imreh.net"}' ${{ steps.deployment.outputs.statuses_url }}

      - name: Update deployment status (success)
        if: failure()
        run: |
          curl -H "Accept: application/vnd.github.ant-man-preview+json" -H "Authorization: token ${{ github.token }}" -X POST -H 'Content-Type: application/json' -d '{"state": "failure", "description": "My failed status"}' ${{ steps.deployment.outputs.statuses_url }}
