name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install curl jq

      # - name: Create deployment
      #   id: deployment
      #   run: |
      #     curl -H "Accept: application/vnd.github.ant-man-preview+json" \
      #      -H "Authorization: token $TOKEN" \
      #      -X POST -H 'Content-Type: application/json' \
      #      -d '{"ref": "curl", "environment": "debug", "transient_environment": true, "description": "My debug env", "required_contexts": []}' \
      #     https://api.github.com/repos/imrehg/deploymentcheck/deployments

      - name: Deploy my app
        run: |
          echo done

      - name: Set var
        run: |
          VAR="1234"
          echo "::set-output name=test::$VAR"
      
      - name: Return var
        run: |
          echo "Var before was: ${{ steps.step2.outputs.test }}"
      # - name: Update deployment status (success)
      #   if: success()

      # - name: Update deployment status (failure)
      #   if: failure()
      #   uses: imrehg/deployment-status@dev
      #   with:
      #     token: "${{ github.token }}"
      #     state: "failure"
      #     deployment_id: ${{ steps.deployment.outputs.deployment_id }}